### ISSUE TITLE
Informations not updated on Discord ?

### ISSUE THREAD

**Issue by Xwilarg** [TheIndra55/chrome-rich-presence#1]
Hi,

I tried this chrome extension, it successfully display informations about the first tab that I refresh but if I refresh another one, the informations on Discord aren't updated.

For exemple:
I launch Discord, I have the chrome://extensions page open
I refresh the tab, informations are displayed on Discord
I open a new tab (for example google.com) and close the previous one
Discord still indefinitely display informations about the extension page

**Comment by TheIndra55** [comment]
The goal of this project was to display the current webpage in discord rich presence **without any external webservers or applications** because of this i could't use named pipes which are officialy used for rich presence in discord. For this extension i'm using the http rpc discord api which seems not always to work perfectly, i tried finding solutions for this problem but couldn't find a fix yet. Feel free to make a pull request if you find a fix for this problem.

**Comment by Xwilarg** [comment]
Thanks for your answer

To be honest I opened an issue here because I'm trying to find a way to update the Rich Presence using a Chrome extension.
